Add IdentityRegistry and rename Registry to MatchRegistry
dojo/core pull request #193
Opened 2016-09-26 13:47 UTC by novemberborn

Include `IdentityRegistry` from `dojo-app`, see <https://github.com/dojo/app/issues/7>.

**This renames `dojo-core/Registry` to `dojo-core/MatchRegistry`**. @kitsonk seemed OK with that back in June when I proposed the rename, but let me know if it's actually a concern.

I can submit PRs for any other repos that reference `dojo-core/Registry` once the rename is approved.

2016-09-26 13:53 UTC, novemberborn commented
Could consider aliasing `dojo-core/Registry` to make releasing easier.

2016-10-03 06:47 UTC, kitsonk reviewed
Also, while not critical, it would be great to add some iterator interfaces to this, like `[Symbol.iterator]`, `entries()`, `values()` and `ids()`.  I guess we could tackle that as a separate issue though.

2016-10-03 06:47 UTC, kitsonk commented on src/IdentityRegistry.ts
> +	hasId(id: Identity): boolean {
Why not `has`?  I can guess you might say "well I am not passing the object" but that is similiar to a Map, in that you pass the [key](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/has), not the object.

2016-10-03 06:47 UTC, kitsonk commented on src/IdentityRegistry.ts
> +	private _entryMap: Map<Identity, Entry<V>>;
Can we stored `_entryMap` and `_idMap` in a WeakMap?

2016-10-03 06:47 UTC, kitsonk commented on src/IdentityRegistry.ts
> +				this._idMap.delete(value);
Deleting from a WeakMap! 😝

2016-10-03 11:00 UTC, novemberborn commented
> Also, while not critical, it would be great to add some iterator interfaces to this, like [Symbol.iterator], entries(), values() and ids(). I guess we could tackle that as a separate issue though.

Yes.

2016-10-03 11:00 UTC, novemberborn commented
Updated.

2016-10-03 11:56 UTC, kitsonk requested changes
Sorry... I should have been more explicit the first time...

2016-10-03 11:56 UTC, kitsonk commented on src/IdentityRegistry.ts
> +		entryMaps.set(this, new Map<Identity, Entry<V>>());
Sorry, to make you do this again, but we have identified an ideal pattern... When we have a 1:1 relationship between private entries in a WeakMap, we should create an interface for managing them and store only one value.  See: dojo/meta#74.  (Or feel free to input on why it is a stupid pattern and we should do something else)

2016-10-03 12:00 UTC, kitsonk commented on src/IdentityRegistry.ts
> +		entryMaps.set(this, new Map<Identity, Entry<V>>());
By the way, you even gave it a 👍 so you must like that pattern!

2016-10-03 12:24 UTC, novemberborn commented on src/IdentityRegistry.ts
> +		entryMaps.set(this, new Map<Identity, Entry<V>>());
Oh yeah! I think I came up with it, no? 😉

2016-10-03 12:33 UTC, novemberborn commented
Updated again.

Used a helper method so the generic value type can be read out of the private state map.

2016-10-03 13:13 UTC, kitsonk approved these changes
👍

2016-10-03 13:19 UTC, merged