improve request/util destructuring
dojo/core pull request #203
Opened 2016-10-04 12:24 UTC by dylans

Suggestion from Kit in reviewing conference talk materials, as a way to improve our usage of destructuring.

2016-10-14 15:33 UTC, kitsonk requested changes
tabs not spaces... should run `grunt` to do a dev build prior to submission 😛

2016-10-26 12:30 UTC, kitsonk commented
Ping...

2016-10-26 15:30 UTC, kitsonk requested changes
Needs a change to compile properly.

2016-10-26 15:30 UTC, kitsonk commented on src/request/util.ts
> +		{ cacheBust }: RequestOptions = {}): string {
`query` needs to be de-structured as well to avoid the issue in line 12 which the compiler is complaining about, because now there is no `options`

2016-10-26 15:49 UTC, dylans commented
@kitsonk should compile properly. Lessons learned:

* Don't copy an example from a conference slide where tabs are converted to spaces
* Avoid grunt/npm hell
* JSDoc doesn't have a proper way to document this syntax (that we know of)

2016-10-27 10:14 UTC, kitsonk requested changes
...

2016-10-27 10:14 UTC, kitsonk commented on src/request/util.ts
> +	let query = new UrlSearchParams(cacheBust.query).toString();
`cacheBust.query` is not a thing...

```ts
export function generateRequestUrl(url: string,
        { cacheBust, query }: RequestOptions = {}): string {
    let query = new UrlSearchParams(query).toString();
```

2016-10-27 10:15 UTC, kitsonk requested changes
...

2016-10-27 10:15 UTC, kitsonk commented on src/request/util.ts
> +	let query = new UrlSearchParams(cacheBust.query).toString();
`cacheBust.query` is not a thing...

```ts
export function generateRequestUrl(url: string,
        { cacheBust, query }: RequestOptions = {}): string {
    let query = new UrlSearchParams(query).toString();
```

2016-10-27 10:18 UTC, kitsonk requested changes
Change in logic from original.

2016-10-27 10:18 UTC, kitsonk commented on src/request/util.ts
> +		query = new UrlSearchParams(query).toString();
This needs to be moved outside of the `if (cacheBust)` to preserve the logic you are replacing

2016-10-27 11:09 UTC, dylans commented
Thanks @kitsonk . It is passing CI, though failing on code coverage (which is unchanged from prior to this PR).

2016-10-27 11:31 UTC, kitsonk approved these changes

2016-10-27 11:40 UTC, kitsonk commented
Actually it is an issue with the way Istanbul is detecting/instrumenting the destructuring in the compiled code.  It is seeing some branches there and they don't get covered in the down emit.

2016-10-27 11:40 UTC, merged