Adding fetch implementation of request api, issue #139
dojo/core pull request #243
Opened 2016-11-21 13:46 UTC by rorticus

Added `request/fetch` for performing requests based on the [`fetch` API](https://fetch.spec.whatwg.org/).

2016-11-21 14:05 UTC, agubler commented on src/request/fetch.ts
> +			let body: any = null;
can you type this as a `Promise<any>` (or not `any` if you know the body type) and then you wouldn't need the `Promise.resolve('body').then,,,` just simply `body.then...`

2016-11-21 14:07 UTC, rorticus commented on src/request/fetch.ts
> +			let body: any = null;
Yes! Good point. I guess I had typed that before I realized it was going to have to be a Promise, and then forgot to change it :/

2016-11-21 14:23 UTC, agubler requested changes
Just a couple minor comments/questions.

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +			let responseHeaders: any = {};
any reason not `const`?

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +			let responseHeaders: any = {};
Also do you know the type of `headers`, presumably something like maybe

```ts
interface Headers {
    [index string]: string;
}
```

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +						let parser = new DOMParser();
`const`?

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +			let { responseType = '' } = options;
`const`?

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +		let auth = options.auth.split(':');
`const`?

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +		for (let header in headers) {
sorry about all the `const` suggestions...

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +			Promise.resolve(body).then((body: any) => {
call this `data` and you can just use `data` in the resolved object and drop the `: body`

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +					const error = new RequestTimeoutError('Request timed out after ' + options.timeout + 'ms');
how about using template literals 

```ts
new RequestTimeoutError(`Request timed out after ${options.timeout}ms`);
```

2016-11-21 14:23 UTC, agubler commented on src/request/fetch.ts
> +				return createHandle(function (): void {
can do if you so desire,

```ts
				return createHandle((): void => {
					clearTimeout(timer);
				});
```

or perhaps even

```ts
			timeout = ((): Handle => {
				const timer = setTimeout((): void => {
					const error = new RequestTimeoutError('Request timed out after ' + options.timeout + 'ms');
					reject(error);
				}, options.timeout);

				return createHandle(clearTimeout.bind(null, timer));
			})();
```

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +		let auth = options.auth.split(':');
Done!

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +		for (let header in headers) {
Done!

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +			let { responseType = '' } = options;
Done!

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +						let parser = new DOMParser();
Done!

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +			let responseHeaders: any = {};
Done!

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +					const error = new RequestTimeoutError('Request timed out after ' + options.timeout + 'ms');
Done!

2016-11-21 14:32 UTC, rorticus commented on src/request/fetch.ts
> +				return createHandle(function (): void {
Done!

2016-11-21 14:48 UTC, agubler commented on src/request/fetch.ts
> +			forOf(fetchResponse.headers.keys(), (key: string) => {
another mainly styling suggestion (I think that works 😉 )

```ts
			forOf(fetchResponse.headers.entries(), ([key, value]) => {
				responseHeaders[ key.toLowerCase() ] = value;
			});
```

2016-11-21 14:55 UTC, agubler commented on src/request/fetch.ts
> +			forOf(fetchResponse.headers.enrties(), ([key, value]) => {
oops typo.

2016-11-21 14:56 UTC, rorticus commented on src/request/fetch.ts
> +			forOf(fetchResponse.headers.enrties(), ([key, value]) => {
Ugh. how did that build? ....

2016-11-21 14:59 UTC, agubler commented on src/request/fetch.ts
> +			forOf(fetchResponse.headers.enrties(), ([key, value]) => {
I really do not know!

2016-11-21 18:09 UTC, agubler commented on src/request/fetch.ts
> +					body = fetchResponse.text().then((asText: string) => {
I believe `.then` should be on a new line as per the style guide

2016-11-21 18:22 UTC, rorticus commented on src/request/fetch.ts
> +					body = fetchResponse.text().then((asText: string) => {
+1

2016-11-23 16:58 UTC, agubler approved these changes
Approved from me! Someone else might want eyes on before the big green light.

2016-12-05 08:49 UTC, agubler commented
Not sure if anyone else will get the opportunity to review this 🎱

2016-12-05 13:06 UTC, dylans commented
A few stray thoughts that are probably worth addressing mostly later as we decide how useful the fetch API might be:

* the fetch API doesn't seem to have a convenience method for json, so the user must explicitly parse json? Is that how our request implementation works also?
* the fetch API seems to implement ReadableStream... I assume we're planning to ignore that for now given the size of the streams shim?
* are we ignoring the type Document (I see we have arraybuffer and blob), or does that get parsed the same way as plain text?
* the fetch API has a number of scenarios around cors, requestType, requestDestination, etc. Do we plan to/need to support these features now or in the future?

2016-12-05 13:58 UTC, rorticus commented
> the fetch API doesn't seem to have a convenience method for json, so the user must explicitly parse json? Is that how our request implementation works also?

We have [a response filter](https://github.com/dojo/core/blob/master/src/request.ts#L198-L207) that runs at a "higher level" that will turn the json type into an actual JSON object.

> the fetch API seems to implement ReadableStream... I assume we're planning to ignore that for now given the size of the streams shim?

I'm OK with ignoring that :)  If we do decide to implement it, we should at least figure out how we're going to pull in `streams` without the dependency in the node request.

> are we ignoring the type Document (I see we have arraybuffer and blob), or does that get parsed the same way as plain text?

It'll get parsed as plain text.

> the fetch API has a number of scenarios around cors, requestType, requestDestination, etc. Do we plan to/need to support these features now or in the future?

That is a great question :) I've ignored them for now because we didn't have anything similar in the xhr/node requests, but adding those options might be a compelling reason why someone would _want_ to use the fetch API over the alternatives.

2016-12-13 15:36 UTC, rorticus commented
Dylan's comments have been split into https://github.com/dojo/core/issues/255 and https://github.com/dojo/core/issues/254 to get this landed.

2016-12-13 15:37 UTC, merged