Using importHelpers instead of noEmitHelpers
dojo/core pull request #368
Opened 2017-11-13 18:28 UTC by rorticus

Using `importHelpers` instead of `noEmitHelpers`. Helpers will be provided by `tslib` but augmented by `@dojo/shim/main`.

2017-11-13 18:32 UTC, bryanforbes approved these changes

2017-11-13 18:33 UTC, bryanforbes requested changes
Can you go through and make sure that where we're using `for...of` that it's not on arrays? Or, if it's on an array, we treat them differently because of https://github.com/Microsoft/TypeScript/issues/19933 .

2017-11-13 19:21 UTC, rorticus commented
@bryanforbes I replaced the array-only usages of `for..of` with `forEach`

2017-11-14 14:39 UTC, bryanforbes commented on src/lang.ts
> +				let value: any = source[ key ];
Why are you adding spaces around `key`?

2017-11-14 15:06 UTC, rorticus commented
@bryanforbes Webstorm was overzealous. I've put back (most) of the style changes. I left ones alone that were fixing previous style errors because of reasons.

2017-11-14 15:09 UTC, bryanforbes requested changes

2017-11-14 15:09 UTC, bryanforbes commented on src/load/util.ts
> +	} else if (isIterable(modules)) {
Should the `else if` be on a new line?

2017-11-14 15:11 UTC, rorticus commented on src/load/util.ts
> +	} else if (isIterable(modules)) {
it is now!

2017-11-14 15:12 UTC, bryanforbes approved these changes

2017-11-14 15:21 UTC, merged